# ── population sizes ───────────────────────────────────────────────────
n_firms:              500        # number of producer / employer agents
n_households:         100        # number of worker / consumer agents
n_banks:              10         # commercial banks

# ── run length ─────────────────────────────────────────────────────────
n_periods:            100        # how many periods Scheduler.run() will iterate

# ── stochastic shock widths ────────────────────────────────────────────
h_rho:                0.10       # production-growth shock cap
h_xi:                 0.05       # wage-growth shock cap
h_phi:                0.10       # bank opex shock cap
h_eta:                0.10       # price-growth shock cap

# ── search frictions ───────────────────────────────────────────────────
max_M:                4          # job applications per unemployed worker
max_H:                2          # loan applications per firm
max_Z:                2          # shops a household can visit

# ── economy-wide structural params ─────────────────────────────────────
theta:                8          # contract length (periods)
beta:                 0.87       # consumption propensity exponent
delta:                0.15       # dividend pay-out ratio
v:                    0.23       # capital-requirement coefficient
r_bar:                0.07       # baseline nominal interest rate
min_wage:             1.0        # statutory minimum wage
min_wage_rev_period:  4          # periods between wage-floor revisions

# ── initial balance-sheet scalars ──────────────────────────────────────
net_worth_init:      10.0
production_init:      1.0
price_init:           1.5
savings_init:         1.0
wage_offer_init:      1.0
equity_base_init: 10000.0

# ── RNG seed (optional) ────────────────────────────────────────────────
seed: 12345            # <- an *int* here; pass a Generator in code to override
