blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/kganitis/bam-engine/issues
    about: Ask a question or start a discussion on the issue tracker.
